<a href="https://colab.research.google.com/github/Metsashka/-3-/blob/master/%22%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_%E2%84%961_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практическое задание №1 "Библиотека NumPy"

1. Создайте массив arr_1 размером 3х4, все элементы которого равны 3.
2. Создайте массив arr_2, заполненный случайными целыми числами от 0 до
9, размером 2х4.
3. Выведите на экран количество элементов в созданных массивах arr_1 и
arr_2.
4. Соедините массивы arr_1 и arr_2 по нулевой оси.
5. Создайте массив arr_3 из кортежа чисел (1, 8, 6, 5, 8, 3) с помощью функции
np.array().
6. Умножьте каждый элемент массива arr_3 на число 3 и прибавьте к каждому
элементу 1. Результат запишите в новый массив arr_4.
7. Преобразуйте масиив arr_3 к двумерному массиву 2х3. Результат запишите
в массив arr_5.
8. Определите минимальные элементы массива arr_5 вдоль первой оси.
9. Вычислите среднее арифметическое всех элементов массива arr_5.
10. Создайте массив arr_6, состоящий из квадратов чисел от 0 до 10.
11. Выведите каждый второй элемент массива arr_6.
12. Выведите элементы массива arr_6 в обратном порядке.
13. Каждому второму элементу массива arr_6 присвойте значение 2.
14. Проверьте, есть ли в массиве arr_6 значение 49.
15. Создайте двумерный массив А, состоящий из положительных и
отрицательных чисел. Из массива A выберите все отрицательные элементы и
запишите их в одномерный массив B.


In [2]:
import numpy as np

In [20]:
# Создание массива arr_1

arr_1 = np.random.randint(3,4, size=(3, 4))
arr_1

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [21]:
# Создание массива arr_2

arr_2 = np.random.randint(0,10, size=(2, 4))
arr_2

array([[4, 2, 2, 3],
       [4, 4, 5, 6]])

In [22]:
# Вывод кол-ва элементов arr_1, arr_2

print("arr_1 size: ", arr_1.size)
print("arr_2 size: ", arr_2.size)

arr_1 size:  12
arr_2 size:  8


In [24]:
# Соединение массивов по нулевой оси
np.concatenate([arr_1, arr_2], axis=0)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [4, 2, 2, 3],
       [4, 4, 5, 6]])

In [26]:
# Создание массива arr_3

arr_3 = np.array([1,8,6,5,8,3])
arr_3

array([1, 8, 6, 5, 8, 3])

In [28]:
# Создание массива arr_4

arr_4 = (arr_3 * 3) + 1

arr_4

array([ 4, 25, 19, 16, 25, 10])

In [43]:
# Создание массива arr_5

arr_5 = np.vstack([arr_3[:3],arr_3[3:]])

arr_5

array([[1, 8, 6],
       [5, 8, 3]])

In [45]:
# Минимум первой оси arr_5

arr_5[1:].min()

3

In [48]:
# Среднее арифмет arr_5

x = np.sum(arr_5)
x=x/arr_5.size
x


5.166666666666667

In [83]:
# Создание массива arr_6

arr_6 = np.arange(0,10)
arr_6 = arr_6*arr_6
arr_6

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [84]:
# Каждый 2 элемент arr_6

arr_6[::2]

array([ 0,  4, 16, 36, 64])

In [69]:
# Вывод arr_6 в обратно порядке

arr_6[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [70]:
# Присвоение каждому 2 элементу arr_6

arr_6[::2] = 2
arr_6

array([ 2,  1,  2,  9,  2, 25,  2, 49,  2, 81])

In [90]:
# Проверка есть ли в массиве arr_6 число 49

np.any(arr_6 == 49)

True

In [111]:
# Создание массива А

A = np.random.randint(-10,10, size=(3, 4))
print(A)
print("====================")

B = A[A<0]
print(B)

[[ 4  5 -6  7]
 [-3  6  2 -6]
 [ 1 -7 -5 -3]]
[-6 -3 -6 -7 -5 -3]
